issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/rules_apko:ref:refs/heads/main
claim_pattern:
  workflow_ref: chainguard-dev/rules_apko/.github/workflows/release.yaml@refs/heads/main

permissions:
  attestations: write
  contents: write
  pull_requests: write
